### ISSUE TITLE
routing tag comparison 

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/doc#63]
We have information how call can be tagged - https://yeti-switch.org/docs/en/yeti-ui-routing/yeti-ui-routing-routing_tags.html#routing-tag

But there is no information about dialpeers/destinations lookup when call is tagged.
https://yeti-switch.org/docs/en/yeti-ui-routing/yeti-ui-routing-dialpeers.html#dialpeer-s-attributes - we need to add information how call tags compared with DP/DST tags.

Links to new page should be from:
1. https://yeti-switch.org/docs/en/yeti-ui-routing/yeti-ui-routing-dialpeers.html#dialpeer-s-attributes
1. https://yeti-switch.org/docs/en/yeti-ui-routing/yeti-ui-routing-destinations.html#destinations
1. https://yeti-switch.org/docs/en/yeti-ui-routing/yeti-ui-routing-routing_tags.html#routing-tag

**Comment by karold-karold** [comment]
Done
